In [ ]:
# Rescaling a Feature
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])

minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))

scaled_feature = minmax_scaler.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [7]:
# Standardizing a Feature

x = np.array([[-1000.1],
              [-200.2],
              [500.5],
              [600.6],
              [9000.9]])

scaler = preprocessing.StandardScaler()

standardized_x = scaler.fit_transform(x)

standardized_x

print("Mean:", round(standardized_x.mean()))
print("Std:", standardized_x.std())

# RobustScaler Method - feature using the median and quartile range
robust_scaler = preprocessing.RobustScaler()

robust_scaler.fit_transform(x)

Mean: 0
Std: 1.0


array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

In [8]:
# Normalizing Observation
from sklearn.preprocessing import Normalizer

features = np.array([[0.5, 0.5],
                     [1.1, 3.4],
                     [1.5, 20.2],
                     [1.63, 34.4],
                     [10.9, 3.3]])

normalizer = Normalizer(norm="l2")

normalizer.fit_transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [ ]:
features_l2_norm = Normalizer(norm='l2').transform(features) # Euclidean Norm (L2)
features_l2_norm

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [11]:
features_l1_norm = Normalizer(norm='l1').transform(features) # Manhattan Norm (L1)
features_l1_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [12]:
print("Sum of the first observation\'s values:",
      features_l1_norm[0,0] + features_l1_norm[0,1])

Sum of the first observation's values: 1.0


In [14]:
# Generating Polynomial and Interaction Features
from sklearn.preprocessing import PolynomialFeatures

features = np.array([[2, 3],
                     [2, 3],
                     [2, 3]])

polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)

polynomial_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

In [16]:
interaction = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)

interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

In [17]:
# Transforming Features
from sklearn.preprocessing import FunctionTransformer

features = np.array([[2, 3],
                     [2, 3],
                     [2, 3]])

def add_ten(x: int) -> int:
    return x + 10

ten_transformer = FunctionTransformer(add_ten)

ten_transformer.transform(features)

array([[12, 13],
       [12, 13],
       [12, 13]])

In [1]:
# Detecting Outliers
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples=10,
                         n_features=2,
                         centers=1,
                         random_state=1)

features[0,0] = 10000
features[0,1] = 10000

outlier_detector = EllipticEnvelope(contamination=.1)

outlier_detector.fit(features)

outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [8]:
# Handling Outliers

# 1st Strategy: Drop/Filter Out the Outliers
import pandas as pd

houses = pd.DataFrame()
houses['Price'] = [534433, 292333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]

houses[houses['Bathrooms'] < 20]

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1  292333        3.5         2500
2  293222        2.0         1500

In [6]:
# 2nd Strategy: Mark Them as Outliers
import numpy as np

houses['Outliers'] = np.where(houses['Bathrooms'] < 20, 0, 1)

houses

Price  Bathrooms  Square_Feet  Outliers
0   534433        2.0         1500         0
1   292333        3.5         2500         0
2   293222        2.0         1500         0
3  4322032      116.0        48000         1

In [7]:
# 3rd Strategy: Transform the Feature to Dampen the Effect of the Outliers

houses['Log_Of_Square_Feet'] = [np.log(x) for x in houses['Square_Feet']]

houses

Price  Bathrooms  Square_Feet  Outliers  Log_Of_Square_Feet
0   534433        2.0         1500         0            7.313220
1   292333        3.5         2500         0            7.824046
2   293222        2.0         1500         0            7.313220
3  4322032      116.0        48000         1           10.778956

In [ ]:
# Discretizating Features
import numpy as np
from sklearn.preprocessing import Binarizer

age = np.array([[6],
                [12],
                [20],
                [36],
                [65]])

binarizer = Binarizer(threshold=18)

binarizer.fit_transform(age)


array([[0],
       [0],
       [1],
       [1],
       [1]])

In [21]:
# multiple threshold
np.digitize(age, bins=[20,30,64])

np.digitize(age, bins=[20,30,64], right=True)

array([[0],
       [0],
       [1],
       [2],
       [3]])

In [27]:
# Grouping Observations Using Clustering
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

features, _ = make_blobs(n_samples=50,
                         n_features=2,
                         centers=3,
                         random_state=1)

dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])

clusterer = KMeans(3, random_state=0)

clusterer.fit(features)

dataframe["group"] = clusterer.predict(features)

dataframe.head(5)

feature_1  feature_2  group
0  -9.877554  -3.336145      2
1  -7.287210  -8.353986      0
2  -6.943061  -7.023744      0
3  -7.440167  -8.791959      0
4  -6.641388  -8.075888      0

In [33]:
# Deleting Observations with Missing Values

# Using Numpy
import numpy as np

features = np.array([[1.1, 11.1],
                     [2.2, 22.2],
                     [3.3, 33.3],
                     [4.4, 44.4],
                    [np.nan, 55]])

features[~np.isnan(features).any(axis=1)]


# Using Pandas
import pandas as pd

dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])
dataframe.dropna()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

In [38]:
# Imputing Missing Values
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples=1000,
                         n_features=2,
                         random_state=1)

scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

true_value = standardized_features[0,0]
standardized_features[0,0] = np.nan

knn_imputer = KNNImputer(n_neighbors=5)
features_knn_imputed = knn_imputer.fit_transform(standardized_features)

print("True Value:", true_value)
print("Imputed Value:", features_knn_imputed[0,0])


True Value: 0.8730186113995938
Imputed Value: 1.0959262913919632


In [46]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples=1000,
                         n_features=2,
                         random_state=1)

scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

true_value = standardized_features[0,0]
standardized_features[0,0] = np.nan

mean_imputer = SimpleImputer(strategy="mean")

feature_mean_imputed = mean_imputer.fit_transform(features)

print("True Value:", true_value)
print("Imputed Value:", feature_mean_imputed[0,0])

True Value: 0.8730186113995938
Imputed Value: -3.058372724614996
